# Generated by Django 4.2.9 on 2024-01-30 17:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default='8b808', editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.UUIDField(auto_created=True, default='4b01a4', editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ratings', models.IntegerField()),
                ('buys', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.PositiveIntegerField()),
                ('title', models.TextField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('seller', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('wishlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=255)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default='c91d9', editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('method', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.userdetails'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfitted.userdetails')),
            ],
        ),
    ]
