# Generated by Django 4.2.9 on 2024-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buys',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
