# Generated by Django 4.2.9 on 2024-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitted', '0002_alter_order_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(auto_created=True, default='facf3', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(auto_created=True, default='b5cf7', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.UUIDField(auto_created=True, default='7cd18a', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
