# Generated by Django 4.2.9 on 2024-01-29 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outfitted', '0002_alter_product_buys_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
